name: 'myntra_clv_dbt'
version: '1.0.0'
config-version: 2
profile: 'myntra_clv'

model-paths: ["models"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

vars:
  silver_lookback_days: 3

models:
  myntra_clv_dbt:
    staging:
      +materialized: incremental
      +incremental_strategy: merge
      +on_schema_change: append_new_columns
      erp:
        +schema: SILVER_ERP
        +tags: ['silver', 'erp']
      crm:
        +schema: SILVER_CRM
        +tags: ['silver', 'crm']
      marketing:
        +schema: SILVER_MARKETING
        +tags: ['silver', 'marketing']

snapshots:
  myntra_clv_dbt:
    +strategy: timestamp
    +updated_at: _FIVETRAN_SYNCED
    +invalidate_hard_deletes: true